import 'dart:io';
import 'package:mason/mason.dart';

bool patchAnchor({
  required HookContext context,
  required String filePath,
  required String anchor,
  required String insertion,
}) {
  final file = File(filePath);

  if (!file.existsSync()) {
    context.logger.warn(
      'Anchor patch skipped: file not found at $filePath\n'
      'Create the file first by running the [feature] brick.',
    );
    return false;
  }

  final original = file.readAsStringSync();

  if (!original.contains(anchor)) {
    context.logger.warn(
      'Anchor patch skipped: anchor "$anchor" not found in $filePath\n'
      'Ensure the file was generated by the [feature] brick.',
    );
    return false;
  }

  if (original.contains(insertion.trim())) {
    context.logger.detail(
      'Anchor patch skipped (idempotent): already present in $filePath',
    );
    return true;
  }

  final patched = original.replaceFirst(
    anchor,
    '${insertion.trimRight()}\n  $anchor',
  );

  file.writeAsStringSync(patched);
  context.logger.success('Patched $filePath');
  return true;
}
