import 'dart:io';
import 'package:mason/mason.dart';

/// Shared utility for safely patching anchor comments in generated files.
///
/// Strategy:
/// 1. Read the target file.
/// 2. Search for the [anchor] comment (e.g. `// mason:repositories`).
/// 3. Build the [insertion] string.
/// 4. Check for idempotency - skip if [insertion] already present.
/// 5. Insert the new content on the line ABOVE the anchor.
/// 6. Write back atomically.
///
/// Fails gracefully:
/// - If the file does not exist, logs a warning and returns false.
/// - If the anchor is not found, logs a warning and returns false.
/// - If the content already exists (idempotency), returns true silently.
bool patchAnchor({
  required HookContext context,
  required String filePath,
  required String anchor,
  required String insertion,
}) {
  final file = File(filePath);

  if (!file.existsSync()) {
    context.logger.warn(
      'Anchor patch skipped: file not found at $filePath\n'
      'Create the file first by running the [feature] brick.',
    );
    return false;
  }

  final original = file.readAsStringSync();

  if (!original.contains(anchor)) {
    context.logger.warn(
      'Anchor patch skipped: anchor "$anchor" not found in $filePath\n'
      'Ensure the file was generated by the [feature] brick.',
    );
    return false;
  }

  // Idempotency check: do not insert if the insertion is already present.
  if (original.contains(insertion.trim())) {
    context.logger.detail(
      'Anchor patch skipped (idempotent): "$insertion" already present in $filePath',
    );
    return true;
  }

  // Insert the content on the line immediately before the anchor comment.
  final patched = original.replaceFirst(
    anchor,
    '${insertion.trimRight()}\n  $anchor',
  );

  file.writeAsStringSync(patched);
  context.logger.success('Patched $filePath with: ${insertion.trim()}');
  return true;
}
